# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cworker.proto\"\x1f\n\x0emapper_request\x12\r\n\x05lines\x18\x01 \x03(\t\"n\n\x0fmapper_response\x12,\n\x06result\x18\x01 \x03(\x0b\x32\x1c.mapper_response.ResultEntry\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32;\n\x06Worker\x12\x31\n\nworker_map\x12\x0f.mapper_request\x1a\x10.mapper_response\"\x00\x62\x06proto3')
)




_MAPPER_REQUEST = _descriptor.Descriptor(
  name='mapper_request',
  full_name='mapper_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lines', full_name='mapper_request.lines', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=47,
)


_MAPPER_RESPONSE_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='mapper_response.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mapper_response.ResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mapper_response.ResultEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=159,
)

_MAPPER_RESPONSE = _descriptor.Descriptor(
  name='mapper_response',
  full_name='mapper_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='mapper_response.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MAPPER_RESPONSE_RESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=159,
)

_MAPPER_RESPONSE_RESULTENTRY.containing_type = _MAPPER_RESPONSE
_MAPPER_RESPONSE.fields_by_name['result'].message_type = _MAPPER_RESPONSE_RESULTENTRY
DESCRIPTOR.message_types_by_name['mapper_request'] = _MAPPER_REQUEST
DESCRIPTOR.message_types_by_name['mapper_response'] = _MAPPER_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mapper_request = _reflection.GeneratedProtocolMessageType('mapper_request', (_message.Message,), {
  'DESCRIPTOR' : _MAPPER_REQUEST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:mapper_request)
  })
_sym_db.RegisterMessage(mapper_request)

mapper_response = _reflection.GeneratedProtocolMessageType('mapper_response', (_message.Message,), {

  'ResultEntry' : _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPPER_RESPONSE_RESULTENTRY,
    '__module__' : 'worker_pb2'
    # @@protoc_insertion_point(class_scope:mapper_response.ResultEntry)
    })
  ,
  'DESCRIPTOR' : _MAPPER_RESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:mapper_response)
  })
_sym_db.RegisterMessage(mapper_response)
_sym_db.RegisterMessage(mapper_response.ResultEntry)


_MAPPER_RESPONSE_RESULTENTRY._options = None

_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='Worker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=161,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='worker_map',
    full_name='Worker.worker_map',
    index=0,
    containing_service=None,
    input_type=_MAPPER_REQUEST,
    output_type=_MAPPER_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
