# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\"\x18\n\x07\x43ommand\x12\r\n\x05value\x18\x02 \x01(\t2+\n\x06GetSet\x12!\n\tOperation\x12\x08.Command\x1a\x08.Command\"\x00\x62\x06proto3')
)




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Command.value', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)



_GETSET = _descriptor.ServiceDescriptor(
  name='GetSet',
  full_name='GetSet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=46,
  serialized_end=89,
  methods=[
  _descriptor.MethodDescriptor(
    name='Operation',
    full_name='GetSet.Operation',
    index=0,
    containing_service=None,
    input_type=_COMMAND,
    output_type=_COMMAND,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETSET)

DESCRIPTOR.services_by_name['GetSet'] = _GETSET

# @@protoc_insertion_point(module_scope)
