# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class GetSetStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Operation = channel.unary_unary(
        '/GetSet/Operation',
        request_serializer=calculator__pb2.Command.SerializeToString,
        response_deserializer=calculator__pb2.Command.FromString,
        )


class GetSetServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Operation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetSetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Operation': grpc.unary_unary_rpc_method_handler(
          servicer.Operation,
          request_deserializer=calculator__pb2.Command.FromString,
          response_serializer=calculator__pb2.Command.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GetSet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
