# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import handler_pb2 as handler__pb2


class WelcomeMessageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.init = channel.unary_unary(
        '/WelcomeMessageService/init',
        request_serializer=handler__pb2.Input.SerializeToString,
        response_deserializer=handler__pb2.Input.FromString,
        )


class WelcomeMessageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def init(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WelcomeMessageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'init': grpc.unary_unary_rpc_method_handler(
          servicer.init,
          request_deserializer=handler__pb2.Input.FromString,
          response_serializer=handler__pb2.Input.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'WelcomeMessageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
